global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ingestor"
    static_configs:
      - targets: ["ingestor:8081"]
    metrics_path: "/metrics"

  - job_name: "feature_service"
    static_configs:
      - targets: ["feature_service:8082"]
    metrics_path: "/metrics"

  - job_name: "inference_service"
    static_configs:
      - targets: ["inference_service:8083"]
    metrics_path: "/metrics"

  - job_name: "api_gateway"
    static_configs:
      - targets: ["api_gateway:8080"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
